### PR TITLE
Package for master

### PR DESCRIPTION
**Pull request by erdoukki**

### CODE REVIEW

**Comment by peci1** [comment]
Should I wait until you finish the review process in the openwrt repo, or do you want this PR to be merged now? Also, I can make you a collaborator in this repo if you'd like ;)

**Comment by erdoukki** [comment]
better to be merged later...
I can also been "upgraded" here if you want !
I have some cleanup to made to the package here, because of the PR to OpenWrt evolutions...

**Comment by peci1** [comment]
Okay, I've added you as a collaborator. Feel free to merge this PR as you like ;)

**Comment by peci1** [comment]
And thanks for the work!

**Comment by erdoukki** [comment]
still got problem with the PR : https://github.com/openwrt/packages/pull/15098 because of an issue on the checks : https://github.com/openwrt/packages/issues/15099

**Pull request merged**
